package mcpImpl

import (
	"context"
	"errors"
	"time"

	"github.com/akolanti/GoAPI/internal/adapter/utils"
	"github.com/akolanti/GoAPI/internal/config"
	"github.com/akolanti/GoAPI/internal/domain/jobModel"
	"github.com/akolanti/GoAPI/internal/job"
)

func ProcessQuery(ctx context.Context, message string, id string) (res QueryResult) {
	//create new job and inject into the job channel
	mcpJob := trackJob{
		QueryResult: QueryResult{
			Id:      id, //this is the id generated by mcp - it will injected as trace (i use em dashes too not just AI ok)
			Query:   message,
			DoRetry: true,
		},
		JobId: utils.GetNewUUID(),
	}

	select {
	case <-ctx.Done():
		mcpJob.DoRetry = false
		mcpJob.Err = errors.New("User cancelled")
	default:
		mcpJob = pollForAnswers(insertJobIntoJobChannel(mcpJob))

	}
	return writeResponseToMCP(mcpJob)
}

func insertJobIntoJobChannel(args trackJob) (mcpJob trackJob) {
	service.CreateJob(job.CreateJobParams{
		ID:       args.JobId,
		ChatID:   utils.GetNewUUID(),
		Message:  args.Query,
		TraceID:  args.Id,
		IsNewChat: true,
	})
	return args
}

func pollForAnswers(args trackJob) (mcpJob trackJob) {
	pollTimes := []int{10, 20, 50, 100, 300, 700, 1000, 2000, 5000, 7000}
	ctx := context.WithValue(context.Background(), config.TRACE_ID_KEY, args.Id)
	timeoutCtx, cancel := context.WithTimeout(ctx, time.Duration(pollTimes[len(pollTimes)-1])*time.Millisecond)
	defer cancel()
	for _, pollTime := range pollTimes {

		select {
		case <-timeoutCtx.Done():
			args.DoRetry = false
			return extractDataFromJob(args, jobModel.Job{}, ctx.Err())
		case <-time.After(time.Millisecond * time.Duration(pollTime)):
			job, isFound := service.GetJobStatus(args.JobId, timeoutCtx)
			if isFound {
				if job.Status == jobModel.JobStatusComplete || job.Status == jobModel.JobStatusError {
					return extractDataFromJob(args, job, nil)
				}
			} else {
				//this is a case that shouldnt really happen since we created the job just now
				return extractDataFromJob(args, jobModel.Job{}, errors.New("job is invalid"))
			}
		}

	}

	return extractDataFromJob(args, jobModel.Job{}, errors.New("No job found"))
}

func extractDataFromJob(args trackJob, job jobModel.Job, err error) (res trackJob) {

	if err != nil {
		args.Err = err
		return args
	}
	args.Status = string(job.Status)
	args.Response = job.JobPayload.Answer
	args.Sources = job.JobPayload.Sources
	return args
}

func writeResponseToMCP(args trackJob) QueryResult {
	return args.QueryResult
}

type QueryResult struct {
	Id       string   `json:"id"`
	Query    string   `json:"query"`
	Response string   `json:"response"`
	Sources  []string `json:"sources"`
	Status   string   `json:"status"`
	Err      error    `json:"err,omitempty"`
	DoRetry  bool     `json:"do_retry"`
}

type trackJob struct {
	QueryResult
	TraceId string `json:"trace_id"`
	JobId   string `json:"job_id"`
}
