// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "me lol"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chat": {
            "post": {
                "description": "Accepts a message, initializes a background processing job, and returns a job ID to track status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messaging"
                ],
                "summary": "Start a new chat job",
                "parameters": [
                    {
                        "description": "Chat Message and optional Chat ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_akolanti_GoAPI_internal_api.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Job successfully created",
                        "schema": {
                            "$ref": "#/definitions/github_com_akolanti_GoAPI_internal_api.InitJobResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request data or chat ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_akolanti_GoAPI_internal_api.JobResponse"
                        }
                    }
                }
            }
        },
        "/ingest": {
            "post": {
                "description": "Receives a file via multipart/form-data, saves it to a temporary directory, and queues an ingestion job.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ingestion"
                ],
                "summary": "Upload a document for ingestion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The display name of the document",
                        "name": "document_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "The PDF or DOCX file to upload",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted - returns job_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request - Missing fields or file too large",
                        "schema": {
                            "$ref": "#/definitions/github_com_akolanti_GoAPI_internal_api.JobResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Storage or Write Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_akolanti_GoAPI_internal_api.JobResponse"
                        }
                    }
                }
            }
        },
        "/status/{id}": {
            "get": {
                "description": "Retrieves the current status of a specific job using its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Job Status"
                ],
                "summary": "Get job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful retrieval of job status",
                        "schema": {
                            "$ref": "#/definitions/github_com_akolanti_GoAPI_internal_api.JobResponse"
                        }
                    },
                    "404": {
                        "description": "Job not found (returns Error object within JobResponse)",
                        "schema": {
                            "$ref": "#/definitions/github_com_akolanti_GoAPI_internal_api.JobResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_akolanti_GoAPI_internal_api.ChatRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "chatID": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_akolanti_GoAPI_internal_api.InitJobResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "status_url": {
                    "type": "string"
                }
            }
        },
        "github_com_akolanti_GoAPI_internal_api.JobOutgoingError": {
            "type": "object",
            "properties": {
                "can_retry": {
                    "type": "boolean",
                    "example": false
                },
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "Job not found"
                }
            }
        },
        "github_com_akolanti_GoAPI_internal_api.JobResponse": {
            "type": "object",
            "properties": {
                "chat_id": {
                    "type": "string",
                    "example": "chat_550"
                },
                "end_time": {
                    "type": "string"
                },
                "error": {
                    "$ref": "#/definitions/github_com_akolanti_GoAPI_internal_api.JobOutgoingError"
                },
                "id": {
                    "type": "string",
                    "example": "job_cz109"
                },
                "result": {
                    "$ref": "#/definitions/github_com_akolanti_GoAPI_internal_api.Result"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "github_com_akolanti_GoAPI_internal_api.RAGResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_akolanti_GoAPI_internal_api.Result": {
            "type": "object",
            "properties": {
                "rag_response": {
                    "$ref": "#/definitions/github_com_akolanti_GoAPI_internal_api.RAGResponse"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Chat RAG API",
	Description:      "This API handles asynchronous chat RAG",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
