package ragBridge

import (
	"context"
	"errors"
	"time"

	"github.com/akolanti/GoAPI/internal/adapter/utils"
	"github.com/akolanti/GoAPI/internal/config"
	"github.com/akolanti/GoAPI/internal/domain/jobModel"
	"github.com/akolanti/GoAPI/internal/handlers"
)

//this package acts as bridge between the rag package and mcp
//it helps me maintain a clean separation of concerns

func ProcessQuery(message string, id string) (res RB_rag) {
	//create new job and inject into the job channel
	mcpJob := RB_trackJob{
		Id:      id, //this is the id generated by mcp - it will injected as trace
		Query:   message,
		Err:     nil,
		DoRetry: true,
		JobId:   utils.GetNewUUID(),
	}
	mcpJob = pollForAnswers(insertJobIntoJobChannel(mcpJob))
	return writeResponseToMCP(mcpJob)
}

func insertJobIntoJobChannel(args RB_trackJob) (mcpJob RB_trackJob) {
	handlers.InsertNewJobForMCP(args.Query, args.Id, args.JobId)
	return args
}

func pollForAnswers(args RB_trackJob) (mcpJob RB_trackJob) {
	pollTimes := []int{10, 20, 50, 100, 300, 700, 1000, 2000, 5000, 7000}
	ctx := context.WithValue(context.Background(), config.TRACE_ID_KEY, args.Id)
	timeoutCtx, _ := context.WithTimeout(ctx, time.Duration(pollTimes[len(pollTimes)-1])*time.Millisecond)
	for _, pollTime := range pollTimes {

		select {
		case <-timeoutCtx.Done():
			args.DoRetry = false
			return extractDataFromJob(args, jobModel.Job{}, ctx.Err())
		case <-time.After(time.Millisecond * time.Duration(pollTime)):
			job, isFound := handlers.GetJobStatus(args.JobId, timeoutCtx)
			if isFound {
				if job.Status == jobModel.JobStatusComplete || job.Status == jobModel.JobStatusError {
					return extractDataFromJob(args, job, nil)
				}
			} else {
				//this is a case that shouldnt really happen since we created the job just now
				return extractDataFromJob(args, jobModel.Job{}, errors.New("job is invalid"))
			}
		}

	}

	return extractDataFromJob(args, jobModel.Job{}, errors.New("No job found"))
}

func extractDataFromJob(args RB_trackJob, job jobModel.Job, err error) (res RB_trackJob) {

	if err != nil {
		args.Err = err
		return args
	}
	args.Status = string(job.Status)
	args.Response = job.JobPayload.Answer
	args.Sources = job.JobPayload.Sources
	return args
}

func writeResponseToMCP(args RB_trackJob) RB_rag {
	return RB_rag{
		Id:       args.Id,
		Query:    args.Query,
		Response: args.Response,
		Sources:  args.Sources,
		Status:   args.Status,
		Err:      args.Err,
		DoRetry:  args.DoRetry,
	}
}
